### PR TITLE
Fixes xxh64 algorithm

### PR DESCRIPTION
**Pull request by leonardocustodio**

### CODE REVIEW

**Comment by leonardocustodio** [comment]
@clangenb this should fix #373 , would you mind to give a shot before I merge it?

**Comment by leonardocustodio** [comment]
Done, added the tests, it seems to be working fine.

**Comment by justkawal** [comment]
@leonardocustodio Genius aye... 💯

**Comment by clangenb** [comment]
Very impressive that you have fixed it this fast.

**Pull request merged**
